config/routes.rb
Rails.application.routes.draw do
  resources :calls
  resources :clients

  devise_for :users, controllers: {
    sessions: "users/sessions"
  }
  get 'home/index'

  get '/users/sign_up', to: redirect('/users/sign_in')
  # Defines the root path route ("/")
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to :user
  belongs_to :client
  belongs_to :reason

  scope :por_cliente_o_razon, -> (name) { joins(:client, :reason).where("clients.name = ? OR reasons.name = ?", name, name)}
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: %i[ show edit update destroy ]

  # GET /calls or /calls.json
  def index
    ccc = params[:cadena]
    if ccc.present?
      @pagy, @calls = pagy(Call.por_cliente_o_razon(ccc))
    else
      @pagy, @calls = pagy(Call.all)
    end
  end

  # GET /calls/1 or /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls or /calls.json
  def create
    @call = Call.new(call_params)
    @call.user = current_user

    respond_to do |format|
      if @call.save
        format.html { redirect_to call_url(@call), notice: "Call was successfully created." }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1 or /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to call_url(@call), notice: "Call was successfully updated." }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1 or /calls/1.json
  def destroy
    @call.destroy

    respond_to do |format|
      format.html { redirect_to calls_url, notice: "Call was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def call_params
      params.require(:call).permit(:client_id, :reason_id)
    end
  end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_call.html.erb
<div id="<%= dom_id call %>">
  <p>
    <strong>User:</strong>
    <%= call.user.email %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= call.client.name %>
  </p>

  <p>
    <strong>Reason:</strong>
    <%= call.reason.name %>
  </p>

</div>

app/views/calls/_form.html.erb
<%= form_with(model: call) do |form| %>
  <% if call.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.select :client_id, Client.all.collect {|c| [c.name, c.id]} %>
  </div>

  <div>
    <%= form.label :reason_id, style: "display: block" %>
    <%= form.select :reason_id, Reason.all.collect {|c| [c.name, c.id]} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render "form", call: @call %>

<br>

<div>
  <%= link_to "Show this call", @call %> |
  <%= link_to "Back to calls", calls_path %>
</div>

app/views/calls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Calls</h1>

<%= form_with method: :get do |form| %>
  <div>
    <%= form.label :cadena, style: "display: block" %>
    <%= form.text_field :cadena %>
    <%= form.submit "Buscar..." %>
  </div>
<% end %>


<% form_with method: :get do |form| %>
  <div>
  <%= form.label :cadena, style: "display: block" %>
  <%= form.text_field :cadena %>
  <%= form.submit "Buscar..." %>
  </div>
<% end %>

<% if @calls.count > 0 %>

<div id="calls">
  <table class="table table-striped">
      <thead>
        <tr>
          <th>Id</th>
          <th>Usuario</th>
          <th>Cliente</th>
          <th>Motivo de la llamada</th>
          <th>Acción</th>
        <tr>
      </thead>
    <% @calls.each do |call| %>
    <tbody>
      <tr>
        <td><%= call.id %></td>
        <td><%= call.user.email %></td>
        <td><%= call.client.name %></td>
        <td><%= call.reason.name %></td>
        <td><%= link_to "Show this call", call %></td>
      <tr>
    </tbody>
  <% end %>
  </table>
</div>
<div class="text-center">
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

<% else %>
  <h2>No hay llamadas para esta consulta</h2>
<% end %>


<%= link_to "New call", new_call_path %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render "form", call: @call %>

<br>

<div>
  <%= link_to "Back to calls", calls_path %>
</div>

app/views/calls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @call %>

<div>
  <%= link_to "Edit this call", edit_call_path(@call) %> |
  <%= link_to "Back to calls", calls_path %>

  <%= button_to "Destroy this call", @call, method: :delete %>
</div>